Add support for shadow DOM #604
clj-commons/etaoin pull request #606
Opened 2024-07-14 03:34 UTC by dgr

Please complete and include the following checklist:

- [x ] I have read [CONTRIBUTING](https://github.com/clj-commons/etaoin/blob/master/CONTRIBUTING.md) and the [Etaoin Developer Guide](https://github.com/clj-commons/etaoin/blob/master/doc/02-developer-guide.adoc).

- [x ] This PR corresponds to an issue that the Etaoin maintainers have agreed to address. 

- [x ] This PR contains test(s) to protect against future regressions

- [x ] I have updated [CHANGELOG.adoc](https://github.com/clj-commons/etaoin/blob/master/CHANGELOG.adoc) with a description of the addressed issue.

2024-07-14 14:41 UTC, lread commented
Nice work @dgr! Thanks for taking so much care!

Some thoughts/ideas/observations:

Maybe docstrings could link to Etaoin user guide which in turn could link to https://wpt.fyi/results/webdriver/tests/classic/find_element_from_shadow_root/find.py?label=experimental&label=master&aligned in a prominent adoc NOTE. This way users would get a link to your very nice overview of the shadow dom (I read, I learned!) AND a link to current implementation limitations. Whaddya think?

Test-doc is failing because code blocks will return different results each time they are run. For example, this gets converted into a test:
```clojure
(e/get-element-shadow-root driver {:id "shadow-root-host"})
;; => "ac5ab914-7f93-427f-a0bf-f7e91098fd37"
```
which expects a return of `"ac5ab914-7f93-427f-a0bf-f7e91098fd37"` always and will therefore fail.

Options:
1. Add a `//:test-doc-blocks/skip` before the code block to have test-doc-blocks skip the code block
2. Remove the `;; =>` lines from the code example, test-doc-block will only expect the code to run without exception and not expect a specific return. If you feel it important the reader of the doc see a typical return, you could instead express that in a comment or descriptive text outside of the code block
3. In some cases, consider rewriting the code sample, for example this:
    ```clojure
    (e/query-shadow-root driver {:id "shadow-root-host"} {:css "#in-shadow"})
    ;; => "30fca382-6d4a-4f8a-9534-db76a1ed7cba"
    (e/get-element-text-el driver "30fca382-6d4a-4f8a-9534-db76a1ed7cba")
    ;; => "I'm in the shadow DOM"
    ```
    Could become:
    ```clojure
    (->> (e/query-shadow-root driver {:id "shadow-root-host"} {:css "#in-shadow"})
         (e/get-element-text-el driver))
    ;; => "I'm in the shadow DOM"
    ```

I reviewed the user guide for what strategy I took for the element id returns, and it looks like I entirely avoided it in code blocks. It seems [I spent a little bit of time upfront describing the difference between -el and non-el variants](https://github.com/clj-commons/etaoin/blob/master/doc/01-user-guide.adoc#selecting-elements) and didn't dwell on it at all later. 

For me, it is a balance between "what does the reader need to see to understand this?" and "can I ensure that the code blocks should always work in the reader's REPL when they try them out?".

Anyhoo, great work, and I am happy to work out the above with you further.

2024-07-14 19:04 UTC, dgr commented
OK, let me do one more commit with updates to doc strings and doc-test stuff.

2024-07-15 19:54 UTC, lread requested changes
Getting real close @dgr! Just a few minor things I noticed.

2024-07-15 19:54 UTC, lread commented on src/etaoin/api.clj
> +  `nil` if the element does not have a shadow root."
I think in all other fns with `q` I've included:

See [[query]] for details on `q`.

2024-07-15 19:54 UTC, lread commented on src/etaoin/api.clj
> +  "First, conducts a standard search (as if by `query`) for an element
If you change `` `query` `` to `[[query]]`, cljdoc will link to the query fn.

2024-07-15 19:54 UTC, lread commented on src/etaoin/api.clj
> +  "First, conducts a standard search (as if by `query`) for an element
If you change `` `query` `` to `[[query]]`, cljdoc will link to the query fn.

2024-07-15 19:54 UTC, lread commented on src/etaoin/api.clj
> +  [driver q shadow-q]
Small typo in link syntax, needs to close with `)` instead of `]`

2024-07-15 19:54 UTC, lread commented on src/etaoin/api.clj
> +  formats (e.g., CSS). See [this note](/doc/01-user-guide.adoc#shadow-root-browser-limitations] for more information."
Small typo in link syntax, needs to close with `)` instead of `]`

2024-07-15 19:54 UTC, lread commented on src/etaoin/api.clj
The namespace docstring includes a toc of sorts. You'll want to add your new fns in there. 
Probably under **Querying/Selecting DOM Elements**

2024-07-15 19:54 UTC, lread commented on doc/01-user-guide.adoc
> +           (map #(e/get-element-text-el driver %)))
minor: indentation

2024-07-15 19:54 UTC, lread commented on doc/01-user-guide.adoc
> +           (map #(e/get-element-text-el driver %)))
minor: identation

2024-07-16 12:42 UTC, dgr commented
OK, try it again.

2024-07-16 14:21 UTC, lread approved these changes

2024-07-16 14:21 UTC, lread commented
Looks great @dgr, thanks!

2024-07-16 14:23 UTC, merged